---

- stat: path="{{ ssh_ecdsa_hostkey }}"
  register: ecdsa_key_stat

- set_fact:
    ssh_hostkey: "{{ ssh_ecdsa_hostkey }}"
  when: "{{ ecdsa_key_stat.stat.exists }}"

- set_fact:
    ssh_hostkey: "{{ ssh_rsa_hostkey }}"
  when: "not {{ ecdsa_key_stat.stat.exists }}"

- name: sshd configuration file update
  template: src=etc-ssh-sshd_config.j2
    dest=/etc/ssh/sshd_config
    backup=yes
    owner=0 group=0 mode=0644
    validate='/usr/sbin/sshd -T -f %s'
  notify:
  - restart sshd
